random_forest:
  n_estimators: [10,50,100,200,500,1000,1500,2000]
  max_depth: [None, 10, 20, 30, 50]
  min_samples_split: [2, 5, 10]
  min_samples_leaf: [1, 2, 5]
  bootstrap: [True, False]
  # criterion: ["gini", "entropy"]


# logistic_regression:
#   penalty: ["l1", "l2", "elasticnet", "none"]
#   C: [0.001, 0.01, 0.1, 1, 10, 100]
#   fit_intercept: [True, False]
#   solver: ["newton-cg", "lbfgs", "liblinear", "sag", "saga"]
#   max_iter: [100, 200, 500]
  
# svc:
#   C: [0.001, 0.01, 0.1, 1, 10]
#   kernel: ["linear", "poly", "rbf", "sigmoid"]
#   degree: [2, 3, 4, 5]  # Only used when kernel is 'poly'
#   gamma: ["scale", "auto"]
#   shrinking: [True, False]
#   max_iter: [-1, 500, 1000, 2000]
