artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://github.com/hrishikesh147/MLProject/raw/main/part_namesz.zip
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion 

data_validation:
  root_dir: artifacts/data_validation
  unzip_dir: artifacts/data_ingestion/part_names.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  data_dir: artifacts/data_ingestion/part_names.csv 

