artifacts_root: artifacts

data_ingestion:
  root_dir: artifacts_root/data_ingestion
  source_URL: https://github.com/hrishikesh147/MLProject/raw/main/part_namesz.zip
  local_data_file: artifacts_root/data_ingestion/data.zip
  unzip_dir: artifacts_root/data_ingestion 

